name: Fetch Meowfacts Daily

on:
  schedule:
    # Runs at 3:05 AM UTC every day
    - cron: '5 3 * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests

      - name: Run the script
        run: python extract_meowfacts.py

      # This step is needed to commit the new JSON file back to your repo
      - name: Commit and push if it changed
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          git add meowfacts_dataset.json
          # The following command will only commit if there are changes
          git commit -m "Update daily meowfacts dataset" || exit 0
          git push